name: Linter
on: push

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name" Checkout code
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Run linter
      uses: github/super-linter@v2.0.0
      env:
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_MD: true
        VALIDATE_JAVASCRIPT_ES: true

